# Generated by Django 2.1.8 on 2019-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190610_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_certainty',
            field=models.CharField(blank=True, choices=[('circa', 'circa')], help_text='If year of publication is uncertain, use circa.', max_length=255, null=True),
        ),
    ]
