# Generated by Django 2.1.8 on 2019-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190610_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerelationship',
            name='sr_category',
            field=models.CharField(choices=[('scriptural citation', 'scriptural citation'), ('attribution', 'attribution'), ('song', 'song'), ('hymn', 'hymn'), ('alto', 'alto'), ('historical note', 'historical note'), ('other content', 'other content')], help_text='Category of relationship', max_length=255, null=True),
        ),
    ]
