# Generated by Django 2.1.8 on 2019-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190610_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrelationship',
            name='pr_category',
            field=models.CharField(choices=[('scriptural citation', 'scriptural citation'), ('attribution', 'attribution'), ('song', 'song'), ('hymn', 'hymn'), ('alto', 'alto'), ('historical note', 'historical note'), ('other content', 'other content')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printingrelationship',
            name='pr_type',
            field=models.CharField(blank=True, choices=[('correction', 'correction'), ('addition', 'addition'), ('alteration', 'alteration')], max_length=255, null=True),
        ),
    ]
