# Generated by Django 2.1.8 on 2019-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190610_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abbreviated_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
