# Generated by Django 2.1.8 on 2019-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190624_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution',
            field=models.CharField(choices=[('composer', 'composer'), ('arranger', 'arranger'), ('hymnwriter', 'hymnwriter'), ('hymn revisor', 'hymn revisor'), ('hymn selector', 'hymn selector'), ('alto', 'alto'), ('treble', 'treble')], max_length=255, null=True),
        ),
    ]
