# Generated by Django 2.1.8 on 2020-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200302_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lines',
            field=models.PositiveIntegerField(choices=[(1, '1'), (3, '3'), (4, '4')], null=True),
        ),
    ]
