# Generated by Django 2.1.8 on 2021-02-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200515_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('female', models.BooleanField(default=False, max_length=255, null=True)),
                ('alternate_spellings', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='attribution_music',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='attribution_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('Aflat', 'A♭'), ('Asharp', 'A♯'), ('B', 'B'), ('Bflat', 'B♭'), ('C', 'C'), ('Csharp', 'C♯'), ('D', 'D'), ('Dflat', 'D♭'), ('Dsharp', 'D♯'), ('Eflat', 'E♭'), ('E', 'E'), ('F', 'F'), ('Fsharp', 'F♯'), ('G', 'G'), ('Gflat', 'G♭'), ('Gsharp', 'G♯')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.CharField(blank=True, choices=[('major', 'major'), ('minor', 'minor'), ('multiple', 'multiple')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lines',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='attributed_person_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributed_person_music', to='app.Person'),
        ),
        migrations.AddField(
            model_name='song',
            name='attributed_person_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributed_person_text', to='app.Person'),
        ),
    ]
