# Generated by Django 2.1.8 on 2021-02-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210202_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_category', models.CharField(choices=[('scriptural citation', 'scriptural citation'), ('attribution', 'attribution'), ('hymn', 'hymn'), ('historical note', 'historical note'), ('other content', 'other content')], help_text='Category of relationship', max_length=255, null=True)),
                ('sr_type', models.CharField(blank=True, choices=[('identical', 'identical'), ('near identical', 'near identical'), ('adapted', 'adapted'), ('direct citation', 'direct citation')], help_text='Type of the relationship', max_length=255, null=True)),
                ('book', models.ForeignKey(help_text='Book that serves as source for song/text unit', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Song')),
                ('text_unit', models.ForeignKey(blank=True, help_text='Section - Page - Sequence', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TextUnit')),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcerelationship',
            name='book',
        ),
        migrations.RemoveField(
            model_name='sourcerelationship',
            name='song',
        ),
        migrations.RemoveField(
            model_name='sourcerelationship',
            name='text_unit',
        ),
        migrations.DeleteModel(
            name='SourceRelationship',
        ),
    ]
