# Generated by Django 2.1.8 on 2021-02-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210202_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_type', models.CharField(blank=True, choices=[('identical', 'identical'), ('near identical', 'near identical'), ('adapted', 'adapted')], help_text='Type of relationship', max_length=255, null=True)),
                ('title_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('page_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('key_in_source', models.CharField(blank=True, choices=[('A', 'A'), ('Aflat', 'A♭'), ('Asharp', 'A♯'), ('B', 'B'), ('Bflat', 'B♭'), ('C', 'C'), ('Csharp', 'C♯'), ('D', 'D'), ('Dflat', 'D♭'), ('Dsharp', 'D♯'), ('Eflat', 'E♭'), ('E', 'E'), ('F', 'F'), ('Fsharp', 'F♯'), ('G', 'G'), ('Gflat', 'G♭'), ('Gsharp', 'G♯')], max_length=255, null=True)),
                ('lines_in_source', models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=255, null=True)),
                ('attribution_text_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution_music_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('attritbuted_person_music_in_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attritbuted_person_music_in_source', to='app.Person')),
                ('attritbuted_person_text_in_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attritbuted_person_text_in_source', to='app.Person')),
                ('book', models.ForeignKey(help_text='Book that serves as source for song', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Song')),
            ],
        ),
    ]
