# Generated by Django 2.1.8 on 2021-02-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_oshaddedalto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltoSourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_type', models.CharField(blank=True, choices=[('identical', 'identical'), ('near identical', 'near identical'), ('adapted', 'adapted')], help_text='Type of relationship', max_length=255, null=True)),
                ('page_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('key_in_source', models.CharField(blank=True, choices=[('A', 'A'), ('Aflat', 'A♭'), ('Asharp', 'A♯'), ('B', 'B'), ('Bflat', 'B♭'), ('C', 'C'), ('Csharp', 'C♯'), ('D', 'D'), ('Dflat', 'D♭'), ('Dsharp', 'D♯'), ('Eflat', 'E♭'), ('E', 'E'), ('F', 'F'), ('Fsharp', 'F♯'), ('G', 'G'), ('Gflat', 'G♭'), ('Gsharp', 'G♯')], max_length=255, null=True)),
                ('mode_in_source', models.CharField(blank=True, choices=[('major', 'major'), ('minor', 'minor'), ('multiple', 'multiple')], max_length=255, null=True)),
                ('attribution_in_source', models.CharField(blank=True, max_length=255, null=True)),
                ('attributed_person_in_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('osh_added_alto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OSHAddedAlto')),
            ],
        ),
    ]
