# Generated by Django 2.1.8 on 2021-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_altosourcerelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='attributed_person_music',
        ),
        migrations.AddField(
            model_name='song',
            name='attributed_person_music',
            field=models.ManyToManyField(blank=True, related_name='attributed_person_music', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='attributed_person_text',
        ),
        migrations.AddField(
            model_name='song',
            name='attributed_person_text',
            field=models.ManyToManyField(blank=True, related_name='attributed_person_text', to='app.Person'),
        ),
    ]
