# Generated by Django 2.1.8 on 2021-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210222_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altosourcerelationship',
            name='attributed_person_in_source',
        ),
        migrations.AddField(
            model_name='altosourcerelationship',
            name='attributed_person_in_source',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='oshaddedalto',
            name='attributed_person_in_ch',
        ),
        migrations.AddField(
            model_name='oshaddedalto',
            name='attributed_person_in_ch',
            field=models.ManyToManyField(blank=True, related_name='attritbuted_person_in_ch', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='oshaddedalto',
            name='attributed_person_in_cooper_sh',
        ),
        migrations.AddField(
            model_name='oshaddedalto',
            name='attributed_person_in_cooper_sh',
            field=models.ManyToManyField(blank=True, related_name='attritbuted_person_in_cooper_sh', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='oshaddedalto',
            name='attributed_person_in_nhc',
        ),
        migrations.AddField(
            model_name='oshaddedalto',
            name='attributed_person_in_nhc',
            field=models.ManyToManyField(blank=True, related_name='attributed_person_in_nhc', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='oshaddedalto',
            name='attributed_person_in_white_sh',
        ),
        migrations.AddField(
            model_name='oshaddedalto',
            name='attributed_person_in_white_sh',
            field=models.ManyToManyField(blank=True, related_name='attributed_person_in_white_sh', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='songsourcerelationship',
            name='attritbuted_person_music_in_source',
        ),
        migrations.AddField(
            model_name='songsourcerelationship',
            name='attritbuted_person_music_in_source',
            field=models.ManyToManyField(blank=True, related_name='attritbuted_person_music_in_source', to='app.Person'),
        ),
        migrations.RemoveField(
            model_name='songsourcerelationship',
            name='attritbuted_person_text_in_source',
        ),
        migrations.AddField(
            model_name='songsourcerelationship',
            name='attritbuted_person_text_in_source',
            field=models.ManyToManyField(blank=True, related_name='attritbuted_person_text_in_source', to='app.Person'),
        ),
    ]
